### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by TheWilley** [TheWilley/LDN#1]
# Bugs and QOL
- [ ] Make the font of the text better in  articles (easier to read)
- [ ] Make all images center in articles (with the exception of the first one)
- [ ] The top image of every article should fit the content container
- [ ] Add the dates and info on the top of articles
- [ ] Add a homepage button

# Features
- [ ] Add a way to change the layout of all articles in the home page!
